### ISSUE TITLE
Updating only the open note's dataview block (rather than all blocks everywhere)?

### ISSUE THREAD

**Issue by JoelAnderson-UU** [udus122/dataview-publisher#50]
I often want to tweak the output of Dataview Publisher before publishing it, but currently running the command `Dataview Publisher: Update dataview publish blocks` refreshes the Dataview Publisher output of ALL file. And so, any customization has to be done for all the notes all over again.

Would it be possible to have the option of restricting the output to only the currently open file?

Thanks for your work on this plugin. It doubles the value of Obsidian Publish!

**Comment by udus122** [comment]
@JoelAnderson-UU Thank you for using dataview-publisher!

How about enabling the "Update on save" setting?

When enabled, when you save a file, only the Dataview Publisher blocks that exist in that file will be updated. (Other files will not be updated.)

**Comment by JoelAnderson-UU** [comment]
I didn’t realize that was the case. That would solve it!
Joel
________________________________
